ALTER TABLE access_tokens RENAME TO access_token;
ALTER TABLE administrators RENAME TO administrator;
ALTER TABLE aws_account_administrators RENAME TO aws_account_administrator;
ALTER TABLE aws_accounts RENAME TO aws_account;
ALTER TABLE blocks RENAME TO block;
ALTER TABLE experiments RENAME TO experiment;
ALTER TABLE participants RENAME TO participant;
ALTER TABLE responses RENAME TO response;
ALTER TABLE templates RENAME TO template;
